apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-cluster-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["get", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ .Chart.Name }}-cluster-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ .Chart.Name }}-cluster-role
subjects:
- kind: ServiceAccount
  name:  {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.webhook.replica_count }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        role: webhook-svc-impl
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
      - name: webhook
        image: {{ .Values.webhook.image }}
        imagePullPolicy: Always
        args: {{ .Values.webhook.cmdargs }}
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /health
            port: {{ .Values.webhook.service_port }}
        ports:
        - containerPort: {{ .Values.webhook.service_port }}
        volumeMounts:
        - name: certs
          mountPath: /home/aiwebhook/certs
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: {{ .Chart.Name }}-cert

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhook.service_name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    role: webhook-svc-impl
  ports:
    - port: {{ .Values.webhook.service_port }}
      targetPort: {{ .Values.webhook.service_port }}
      name: {{ .Chart.Name }}-svc