# Default values for ai-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

webhook:
  # -v 2 enables verbose logging for testing
  cmdargs: '["--logtostderr", "-v=2"]'
  image: appinsights-webhook:latest
  service_port: 443
  replica_count: 1
  service_name: appinsights-webhook-svc